-- PeakDrive schema. Idempotent so it can be applied to a database that was
-- previously managed by EF Core migrations without dropping data.
-- Matches the final state of the ditDriveAPI EF Core migration chain.

CREATE TABLE IF NOT EXISTS "Users" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email"        text NOT NULL,
    "PasswordHash" text NOT NULL DEFAULT '',
    "Role"         integer NOT NULL DEFAULT 0,
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");

CREATE TABLE IF NOT EXISTS "Folders" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"    integer NOT NULL,
    "PublicId"  text NOT NULL DEFAULT '',
    "Name"      text NOT NULL,
    "ParentId"  integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "FK_Folders_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Folders_Folders_ParentId" FOREIGN KEY ("ParentId")
        REFERENCES "Folders" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Folders_PublicId" ON "Folders" ("PublicId");
CREATE INDEX IF NOT EXISTS "IX_Folders_UserId" ON "Folders" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Folders_ParentId" ON "Folders" ("ParentId");
CREATE INDEX IF NOT EXISTS "IX_Folders_DeletedAt" ON "Folders" ("DeletedAt");

CREATE TABLE IF NOT EXISTS "Files" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        integer NOT NULL,
    "FolderId"      integer,
    "PublicId"      text NOT NULL DEFAULT '',
    "Filename"      text NOT NULL,
    "StoredName"    text NOT NULL,
    "ThumbnailName" text,
    "FileType"      text NOT NULL,
    "Size"          bigint NOT NULL,
    "UploadedAt"    timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt"     timestamp with time zone,
    CONSTRAINT "FK_Files_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Files_Folders_FolderId" FOREIGN KEY ("FolderId")
        REFERENCES "Folders" ("Id") ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Files_PublicId" ON "Files" ("PublicId");
CREATE INDEX IF NOT EXISTS "IX_Files_UserId" ON "Files" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Files_FolderId" ON "Files" ("FolderId");
CREATE INDEX IF NOT EXISTS "IX_Files_DeletedAt" ON "Files" ("DeletedAt");

CREATE TABLE IF NOT EXISTS "Shares" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FileId"    integer,
    "FolderId"  integer,
    "Token"     text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "FK_Shares_Files_FileId" FOREIGN KEY ("FileId")
        REFERENCES "Files" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Shares_Folders_FolderId" FOREIGN KEY ("FolderId")
        REFERENCES "Folders" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Shares_Token" ON "Shares" ("Token");
CREATE INDEX IF NOT EXISTS "IX_Shares_FileId" ON "Shares" ("FileId");
CREATE INDEX IF NOT EXISTS "IX_Shares_FolderId" ON "Shares" ("FolderId");

CREATE TABLE IF NOT EXISTS "ActivityLogs" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"    integer,
    "Action"    text NOT NULL,
    "Status"    text NOT NULL,
    "Message"   text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "FK_ActivityLogs_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_CreatedAt" ON "ActivityLogs" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_UserId" ON "ActivityLogs" ("UserId");

CREATE TABLE IF NOT EXISTS "SavedItems" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"     integer NOT NULL,
    "TargetType" text NOT NULL,
    "TargetId"   integer NOT NULL,
    "SavedAt"    timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "FK_SavedItems_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_SavedItems_SavedAt" ON "SavedItems" ("SavedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SavedItems_UserId_TargetType_TargetId"
    ON "SavedItems" ("UserId", "TargetType", "TargetId");
